


spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/db_oauth2?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: nhanbn98
server:
  port: 9090
